version: '3.7'

services:
    web:
        container_name: web
        build: .
        restart: always
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        links:
            - db
        ports:
            - 3333:3333
        command: yarn dev

    db:
        image: mongo:latest
        container_name: db
        restart: always
        env_file:
            - .env
        ports:
            - '27017:27017'
        volumes:
            - dbdata-volume:/data/db
        environment:
            MONGO_INITDB_USERNAME:
            MONGO_INITDB_PASSWORD:
            MONGO_INITDB_DATABASE: imageSystem

volumes:
    dbdata-volume: